### PR TITLE
[FIX] compatibility with phpdocumentor/reflection 4.0.1 and multiple fix

### PR DESCRIPTION
**Pull request by luri-fr**
Hi,
I want use this project for some personale work but this not working actually.
I make some change for fix that : 
- Update composer.json for use only stable lib
- Modify Middleware and ProjectFactory creation to adapt with change in phpDocumentor/Reflection
- Fix phpunit compatibility
- Fix InvalidTag problem (some @param can be invalidTag)

I've tested with a personnal lib with php cli 7.2.34 NTS x64 (Win7) and php cli 8.0.0 NTS x64 (Win7).

This is my first pull request on my life. Be comprehensive, thanks

### CODE REVIEW

**Comment by luri-fr** [comment]
I don't know why coverage pass for 87,7% to 0%. Any help please ?

**Comment by luri-fr** [comment]
I test revert change introduced by commit 8b7dceb but this not work.

**Comment by luri-fr** [comment]
I found why coverage is down to 0% : Package codacy/coverage is abandoned. 

@abbadon1334 can you fix that ? A remplacement is https://github.com/codacy/codacy-coverage-reporter

**Comment by luri-fr** [comment]
Add 3 fix : 
- We have error if we not provide extension --> 077f616
- TocExtension display private method even if PublicOnlyExtension and/or NoPrivateExtension is up --> a1fe71a
- Delete "properties" sub title if we have no properties displayed. (private properties with NoPrivateExtension is up) --> d87fbd1

**Comment by abbadon1334** [comment]
@luri-fr thx I will look further in coverage

**Comment by abbadon1334** [comment]
sorry for possible spam @luri-fr. It was a pain in the ass solving a stupid issue :) but now works as excepted. Have a good day.

**Pull request merged**
